apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: nameofokja/kube-story-data:latest
          imagePullPolicy: Always
          env:
            - name: STORY_FOLDER # proccess.env.STORY_FOLDER
              # value: 'story' :: key value
              valueFrom:
                configMapKeyRef:
                  name: test-story-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume ## vloumes의 volume name
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: test-host-pvc
        #
        # - name: story-volume
        #   hostPath:
        #     path: /story-data
        #     type: DirectoryOrCreate
        #
        # - name: story-volume
        #   emptyDir: {}
