apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-host-pv
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  storageClassName: standard # kubectl get sc 해서 나온 default 값
  accessModes:
    - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  hostPath:
    path: /data
    type: DirectoryOrCreate
