apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-host-pvc
spec:
  volumeName: test-host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
