apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: second-app
  ports:
    - name: second-app-tcp-port
      protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-nodejs
          image: nameofokja/kube-first-app:2
