apiVersion: v1
kind: Service
metadata:
  name: backend-service
  # labels:
  #   group: example
spec:
  selector:
    app: second-app
  ports:
    - name: second-app-tcp-port
      protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
