apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: nameofokja/kube-test-users
          imagePullPolicy: Always
          env:
            - name: AUTH_ADDRESS
              # value: '10.101.36.148'
              # 서비스이름.네임스페이스
              value: 'auth-service.default'
